#pragma once
#include <imgui_icon_font_headers/IconsFontAwesome5.h>

#define BUNSEN_ICON_RENDERER ICON_FA_MICROCHIP
#define BUNSEN_ICON_WORLD ICON_FA_GLOBE_EUROPE
#define BUNSEN_ICON_MODEL ICON_FA_CUBE
#define BUNSEN_ICON_MESH ICON_FA_DRAW_POLYGON
#define BUNSEN_ICON_MATERIAL ICON_FA_GEM
#define BUNSEN_ICON_LIGHT ICON_FA_LIGHTBULB
#define BUNSEN_ICON_CAMERA ICON_FA_VIDEO